apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment-deployment
  labels:
    app: devops-assignment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-assignment
  template:
    metadata:
      labels:
        app: devops-assignment
    spec:
      containers:
      - name: devops-assignment-container
        image: badfella/devops-assignment
        ports:
        - containerPort: 8000
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: devops-assignment-rollout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-assignment
  strategy:
    blueGreen:
      activeService: devops-assignment-service
      previewService: devops-assignment-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: devops-assignment
    spec:
      containers:
      - name: devops-assignment
        image: badfella/devops-assignment:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-assignment-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: devops-assignment
---
apiVersion: v1
kind: Service
metadata:
  name: devops-assignment-preview-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: devops-assignment